### ISSUE TITLE
[Bug] Missing character backgrounds/banners

### ISSUE THREAD

**Issue by soleilvermeil** [eikofee/eikonomiya-front#18]
**Describe the bug**
Some characters have a blank background, namely (not exhaustive list, I haven't checked everyone):
* Lumine
* Aether
* Kuki
* Kazuha

I guess it is not surprising for the traveller to have no banner, but just in case.

**Screenshots**
![image](https://github.com/eikofee/eikonomiya/assets/100100316/faf7468b-2ce8-4f01-8097-58c1c0c373a4)
![image](https://github.com/eikofee/eikonomiya/assets/100100316/85a3df21-6b19-43af-9048-b410dabb9389)
![image](https://github.com/eikofee/eikonomiya/assets/100100316/daf40f4d-e017-4407-b187-bc2c6279e3b2)

**Comment by eikofee** [comment]
fixed in cb244b902b673052236ccef41e2875db77196e26 and 61f884860b32141ca762b3746a450494d6fbdb02.
There is indeed no namecards for the Traveler, but I put the one from the [Meetings in Outrealm: Series IV](https://antifandom.com/genshin-impact/wiki/Meetings_in_Outrealm:_Series_IV) achievement. It should be fitting enough for them.
